### ISSUE TITLE
Payload may not be larger than...

### ISSUE THREAD

**Issue by xvolution** [pixlepix/Aura-Cascade#102]
A player on a server I help administrate gets the following error when he tries to log in:

[Disconnect] User <redacted> has disconnected, reason: Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 2097050 bytes

The issue turned out to be his player file being corrupted.  After using a NBT editor to thoroughly check his player file, I spotted something odd in his ACQuest --> questArray entry.

questArray: 2097152 integers

All evidence points to the questArray entry being the cause of the corruption, but I have no idea why it would be that high. He mentioned that he hasn't even touched this mod, so in theory that integer value shouldn't be that high.

**Comment by GirafiStudios** [comment]
What version of Aura Cascade are you using?

**Comment by xvolution** [comment]
AuraCascade-557.jar

**Comment by AdlyTempleton** [comment]
No longer relavent
