### ISSUE TITLE
Aura Capacitors can get stuck [557]

### ISSUE THREAD

**Issue by OisiGreen** [pixlepix/Aura-Cascade#103]
This happened on simply magic 1.14.
https://gfycat.com/DrearyWatchfulAardwolf

The same setup consistently gets stuck like this in a matter of minutes.

**Comment by GarradStacey** [comment]
I can confirm with a similar violet aura setup using capacitors that they appear to get stuck as well. I think it might be related to the node receiving enough aura to cap it (so over 1000 in one go) in the same 'aura balancing tick' that the cooldown starts on. A way to reduce the rate this happens is to replace that block you have in the middle with an aura node - although this does slow down the aura capacitors somewhat.

**Comment by ANTdentarg** [comment]
yay, just encountered this issue and fixed it (finally) by placing nodes on the same horizontal plane as the receiving node(s). don't know why this happens, nor do I know why that fixed it.
