### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Ryahn** [pixlepix/Aura-Cascade#104]
We are getting spam in our server log with the following. We were able to trace it back to this mod and were wondering if there is a fix or way to turn it off.

`[de.npe.gameanalytics.EventHandler$RESTHelper:sendData:209]: Failed to send analytics event data. Result of attempt: ok | Authentication hash used: a9b26ba7c8b91f892782818e8b7a99f6 | Data sent: [{"install_publisher":"1.8.0_73-b02","install_site":"server","install_campaign":"3.13.0-24-generic","install_adgroup":"amd64","install_ad":"Linux","install_keyword":"server","user_id":"server8074143c-0261-48a1-91f8-c48a9f1af099","session_id":"1456228982764","build":"591"}]`

https://pastebin.com/TvxTEBEd

EDIT: We have also turned the config option for sending analytic to false and still spams

**Comment by jikuja** [comment]
Try disabling Mc snooper. GA framework should disable itself if MC snooper is disabled.

There seems to be two bugs: 
1. in the framework: fixed in https://github.com/NPException/GameAnalyticsAPI/commit/822ecb9f7a45adb2251dfdecdf2edb490359759f
2. https://github.com/pixlepix/Aura-Cascade/blob/master/src/main/java/pixlepix/auracascade/main/Config.java#L59 analytics variable is never set when reading config file

**Comment by Galaxy2Alex** [comment]
Why is there an analytics tool anyway? It seems very shady to include one in a mod.

**Comment by Ryahn** [comment]
@Galaxy2Alex Thats what I am thinking 

@jikuja I have disabled MC snooper and resolved the issue.

**Comment by jikuja** [comment]
Please reopen. Bugs are still in the code.

**Comment by NPException** [comment]
@Galaxy2Alex, just to lower your concerns: My GA-API that is used by aura cascade enables mods (or any game written in Java) to send anonymous usage data to [GameAnalytics](http://www.gameanalytics.com/). No information about your MC account is ever sent to them. The only data that is collected anonymously by default are:

* Language that is set in MC
* Type of CPU
* Name of Operating System
* Version of Operating System
* Java version used
* Whether this is a Client or a Server

Mods can queue the sending of additional events, in case of Aura Cascade for example (if I interpret the code correctly):

* A quest was finished
* An Aura of some color was used

As far as I can tell, Aura Cascade is not sending anything that could be directly linked to users MC account, and is therefore collecting only anonymous data.
