### ISSUE TITLE
1.8 Crashlog

### ISSUE THREAD

**Issue by RaineAndrews** [pixlepix/Aura-Cascade#105]
latest.log - [http://pastebin.com/LRZL9cTu]

[fml-client-3.txt](https://github.com/pixlepix/Aura-Cascade/files/146708/fml-client-3.txt)

Crashed twice thusfar when looking at "More Power" page.  Doesn't happen everytime

**Comment by williewillus** [comment]
please report to my repo for 1.8

**Comment by pixlepix** [comment]
Closing this as duplicate
