### ISSUE TITLE
Crash when viewing the multiblock in the lexicon

### ISSUE THREAD

**Issue by Yavin7** [pixlepix/Aura-Cascade#107]
fml-client.log: [fml-client-1.txt](https://github.com/pixlepix/Aura-Cascade/files/226015/fml-client-1.txt)
crash-log: [crash-2016-04-19_08.48.24-client.txt](https://github.com/pixlepix/Aura-Cascade/files/226030/crash-2016-04-19_08.48.24-client.txt)
modpack: The Pioneers on Curse

**Comment by MrTubzy456** [comment]
I've had the same exact issue recently. It's in the introduction section when you look at energy storage.

**Comment by pixlepix** [comment]
Can't reproduce, probably fixed upstream
