### ISSUE TITLE
Bookshelves can be accessed through AE2 storage bus

### ISSUE THREAD

**Issue by pixlepix** [pixlepix/Aura-Cascade#25]

**Comment by Yulife** [comment]
I don't think this is a good balance point. From what I've seen the Bookshelves are similar to an AE-Network and it would be making them kind of redunant if they are compatible with AE2. Correct me if I am wrong!

**Comment by akvgergo** [comment]
Related crash: http://hastebin.com/cuhiziyomu
(Tried to insert a storage book into the bookshelf)
