### ISSUE TITLE
Crash with duplicate enchantment ids with ars magica 2

### ISSUE THREAD

**Issue by aldra2012** [pixlepix/Aura-Cascade#28]
unfortunately it seems you can't change the id in the aura cascade config so here i am http://pastebin.com/E3McQDRE

Build 224

**Comment by aldra2012** [comment]
all builds beyond 222 crash because the enchantment ids are conflicting with ars magica 2 please fix

**Comment by pixlepix** [comment]
The builds on jenkins are experimental development builds. It *will* be fixed before it is released, but use regular builds until then. Impatience gets you nowhere.

**Comment by pixlepix** [comment]
Fixed

**Comment by aldra2012** [comment]
my apology for being impatient and rude to you. I really love your mod,
