### ISSUE TITLE
Traveler's bricks issues.

### ISSUE THREAD

**Issue by Aulton** [pixlepix/Aura-Cascade#29]
So we have Aura cascade on our server, and someone tried out the traveler's bricks, this ensued some rather fun 'testing' sessions. First issue, with a jump boost item, if you jump wile running against the blocks, you actually get launched about 120 blocks into the air, depending on the jump boost level. The speed is ridiculous when mixed with speed boost items (Sojourner's Wyvern Armor, etc.). Also, because it's not a full bock or a slab, you get stuck inside of it alot. We had to teleport a few people because they were glitched into the air, and breaking the bricks didn't change anything.

**Comment by pixlepix** [comment]
Can you elaborate on the 'they were glitched into the air' and 'you get stuck inside of it a lot'? Screenshots would be ideal.

**Comment by Aulton** [comment]
Well, there wasn't really anything we could do for screenshots, as each person saw the player as being above the blocks, like he was standing on a full block, but he was stuck there. We had to forcibly teleport him out of the 'prison' via op commands. This usually happened through the player running too fast back and forth along the road, mostly having a speed up item to mess with the speed. Also, I'm not sure if it's intended, but it also seems to exponentially propel items along the path, meaning if you toss a cobblestone along the path, it turns into the minecraft equivelent to a particle accelerator.
