### ISSUE TITLE
[bug] Fairy issue

### ISSUE THREAD

**Issue by w1zzard1990** [pixlepix/Aura-Cascade#31]
currently playing material energy^4 made a few fairies, made a fetcher fairy equipped it while having a  basic fairy in my hot bar as well placed both in the ring as fetcher fairies.
when i removed them from the ring both stayed as the fetchers.

**Comment by pixlepix** [comment]
Not sure exactly what your saying here, especially with the "when i removed them from the ring both stayed as the fetchers". Could you be a bit more specific.

**Comment by w1zzard1990** [comment]
u shift right click the ring to remove the fairies from the ring, thought it may have just been labeling the fairy wrong after placing it in, but both came out as  fairy fetcher.

 in inventory: 1 fairy 1 fairy fetcher. right click fairy fetcher into ring. both disappear into ring and are listed as fairy fetcher.

**Comment by w1zzard1990** [comment]
been unable to replicate, not exactly sure how it happened. tho i did notice while testing that the charms dont check if the ring is full when u use them.
if u use a charm when full it seems to destroy the charm

**Comment by w1zzard1990** [comment]
managed to replicate the issue ill try and do some screenshots to demonstrate

**Comment by w1zzard1990** [comment]
http://imgur.com/a/2yTMt
hope this helps

**Comment by w1zzard1990** [comment]
just tested with  different types of fairy and issue seems to only happen when you are shift right clicking a fairy that is on the right of another fairy in your hot bar.
