### ISSUE TITLE
Crash when using Remain in Motion due to malformed IMC

### ISSUE THREAD

**Issue by planetguy32** [pixlepix/Aura-Cascade#37]
Reported by Amaxter: http://hastebin.com/abuperuxab.coffee

At [this line](https://github.com/pixlepix/Aura-Cascade/blob/master/src/main/java/pixlepix/auracascade/block/AuraBlock.java#L60),  you send the blacklisting IMC message, but getNameForObject() returns null until the object has been registered so the IMC goes out with "null" as the block.

**Comment by Amaxter** [comment]
Can confirm, love the mod and can't wait for a fix!
