### ISSUE TITLE
Thaumcraft Vis relay crash

### ISSUE THREAD

**Issue by GreatOrator** [pixlepix/Aura-Cascade#39]
When placing any of the nodes next to a thaumcraft vis relay this crash happoens:

http://pastebin.com/iGfUwfCS

Until I edit out the auracascade block the server goes into an infinite reboot cycle and the map cannot be entered.

**Comment by pixlepix** [comment]
This was reported last night. As far as I can tell, this isn't my problem, just the fact that aura nodes trigger block updates occasionally.
