### ISSUE TITLE
[SUGGESTION]: Option to Not Start with Book

### ISSUE THREAD

**Issue by Amaxter** [pixlepix/Aura-Cascade#58]
Hello, I love your mod and use it in an (intentionally) kitchen sink pack of mine, and would like the option to disable spawning with the Encyclopedia Aura. Why? Because my pack is intended to be appeal to a diverse group of players, and for those not interested in magical stuff will likely throw it away and consider it a nuisance, while those who want to pursue it can craft it themselves. If you could add this option in the config that would be great, thank you.

**Comment by akvgergo** [comment]
We already have that. it's literally the first option in the configuration file. What version are you using?

**Comment by pixlepix** [comment]
Yep, this already exists. Closing. If you don't see the config option, please reopen as that is a technical issue (though I can't imagien why that would happen
