### ISSUE TITLE
Book Coordinator causing massive frame hit and freezes

### ISSUE THREAD

**Issue by lurch1985** [pixlepix/Aura-Cascade#59]
Getting a big frame hit and constant freezing shortly after placing the Bookshelf Coordinator.  This occurred in java version 1.8.0_45.  Reverting to an older java version (1.7.0_79) fixes all of the issues.

Thought you might like to know.  Thanks for such an interesting mod!

EDIT:  On further testing, changing the java version hasn't fixed it, merely slowed it down a little.  The problem doesn't appear to start until you power the Coordinator.  I was using a basic 4 node illuminator if this makes any difference.

CPU usage starts out fine, but after a short time (ranging between seconds to minutes), CPU usage starts to spike repeatedly.  Memory usage doesn't seem affected.

Also, I'm running fastcraft as part of the FTB: Daybreaker modpack.

EDIT2:  In further news, relogging into the game doesn't fix client performance, a full client restart is required.  Also, on exiting minecraft a java service remains active and keeps eating up CPU causing the FTB launcher to crash (I know this isn't your problem. :))

Additionally, this doesn't seem to affect other people on my server, only myself, so I'm not sure if it's a problem with my PC configuration or if you'll be able to reproduce this.

Hoping this info helps diagnose the problem.  Feel free to ask for specifics if you need anything more.

**Comment by pixlepix** [comment]
Any way at all you would be able to run some sort of java profiler? Reproducing this looks to be a challenge

**Comment by pixlepix** [comment]
Is there any automated interaction with the system? Does it persist when moving to a different area?

**Comment by lurch1985** [comment]
Sorry, didn't get a chance to check yesterday.  If you could suggest a suitable profiler, I'll be happy to give it a go.  And the problem starts as soon as the system is powered without any automation attached.  Only a few bookcases with storage books inserted.

**Comment by pixlepix** [comment]
https://visualvm.java.net/download.html is a good profiler. Look for methods with high cpu usage containing 'pixlepix'. You want to use the profiler, the last tab on the right.

**Comment by lurch1985** [comment]
Unfortunately, it seems I can't seem to reproduce it now.  No idea what changed, but it's no longer causing any problems.  It must have been some quirk on my PC configuration. I guess as long as it's not affecting anyone else, that's a good thing!

Thanks for your work on the mod!  Keep it up. :D
