### ISSUE TITLE
Crash with Angel Steel Sword

### ISSUE THREAD

**Issue by Gideonseymour** [pixlepix/Aura-Cascade#60]
http://paste.feed-the-beast.com/view/e6c68de0

**Comment by pixlepix** [comment]
Any context/any way to reproduce? A quick look makes it seem like NBT on an item got erased.

**Comment by akvgergo** [comment]
I managed to replicate it (Identical crashlogs) with a sword that I got using /give. It crashed in the moment I tried to equip it.
