### ISSUE TITLE
[Suggestion] Cascading Fisher

### ISSUE THREAD

**Issue by Ayrrow** [pixlepix/Aura-Cascade#67]
Just an early-ish game block that could be placed over water (say a 3x3x3 pool minimum) that fishes.

**Comment by pixlepix** [comment]
I like this alot, actually. Need more early game consumers. Will implement

On Tue, Jul 7, 2015 at 8:59 AM, Ayrrow <notifications@github.com> wrote:

> Just an early-ish game block that could be placed over water (say a 3*3*3
> pool minimum) that fishes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixlepix/Aura-Cascade/issues/67>.
>



-- 
This message has been encrpyted with ROT-13 twice for double security.
