### ISSUE TITLE
Fluxing node is not working with Immersive Engineering machines

### ISSUE THREAD

**Issue by Kubuxu** [pixlepix/Aura-Cascade#69]

**Comment by Ayrrow** [comment]
What version of Immersive Engineering are you using? Its working for me just fine with 0.4.0

**Comment by Kubuxu** [comment]
Try multiblock machines like excavator.

**Comment by Ayrrow** [comment]
try copying what you see above.

**Comment by Kubuxu** [comment]
The node is angry on the connector.
I am using v504.

**Comment by pixlepix** [comment]
Assuming you meant https://github.com/pixlepix/Aura-Cascade/commit/ecd66bea1e74362dee5b65a60bedc165bc7dc961, that wouldn't fix it (Well, I would be very surprised)

**Comment by Kubuxu** [comment]
I've meant that. Copied wrong commit.

I can't place the fluxing node near capacitor, connector, nor multiblock structure.
