### ISSUE TITLE
What do you think of this?

### ISSUE THREAD

**Issue by TheDoctorSoda** [pixlepix/Aura-Cascade#71]
I did some texture modifying. Here's what I think: The gem textures in this mod make it look like it's one of those thousands of "More Ores" mods. I decided to give the gems their own textures, even though they're made from diamonds. For now I left the ingots, but I might make them shinier in the future. I also changed the three swords slightly.

Also, sorry I wasn't able to do a PR, because I couldn't figure out how to update my local repository. https://github.com/TheDoctorSoda/Aura-Cascade

If you approve, I'll take a loot at blocks next.

**Comment by pixlepix** [comment]
Love this - could use some better textures. Will add when I get home. Come
onto #auracascade to chat!

On Thu, Jul 9, 2015 at 2:03 PM, Soda <notifications@github.com> wrote:

> I did some texture modifying. Here's what I think: The gem textures in
> this mod make it look like it's one of those thousands of "More Ores" mods.
> I decided to give the gems their own textures, even though they're made
> from diamonds. For now I left the ingots, but I might make them shinier in
> the future. I also changed the three swords slightly.
>
> Also, sorry I wasn't able to do a PR, because I couldn't figure out how to
> update my local repository. https://github.com/TheDoctorSoda/Aura-Cascade
>
> If you approve, I'll take a loot at blocks next.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixlepix/Aura-Cascade/issues/71>.
>



-- 
This message has been encrpyted with ROT-13 twice for double security.

**Comment by pixlepix** [comment]
Though *please* don't touch anything you don't absolutely have to in the repo for any future updates. Makes it much harder to merge in

**Comment by pixlepix** [comment]
Implemented

**Comment by TheDoctorSoda** [comment]
Sorry I completely forgot to check back to see if you had replied! What timezone are you at?

**Comment by TheDoctorSoda** [comment]
@pixlepix I'll try to be on #Auracascade as often as I can.
