### ISSUE TITLE
Infinite Gold/Aura using Vortex Infusion

### ISSUE THREAD

**Issue by kyahco** [pixlepix/Aura-Cascade#74]
It seem that using Vortex Infusion it is possible to obtain infinite gold or Aura. 

Basically the problems lies in the fact that Aura crystals are made from gold and gold blocks and can be created by Vortex Infusion. It only takes 40,000 power, which each Aura crystal give 1000 Aura, used on a node 16 blocks above pedestal you get about 16,000 power (more or less). This means using only around 2-4 Aura Crystals I can make one gold block, it only cost me only 1-2 nuggets of gold (as 8 nuggets = 16 Crystals). I can then use the new gold to make more crystals and grain free gold and Aura.

Now I know it also takes 4 iron blocks, but using ore doubling, as well as other mods, the Iron can become meaningless in the end. Really considering you can't really control for what resources other mods can mass reproduce, any resource being used can be considered negligible in the quest for infinite gold or Aura.

I really love this Mod and it's ideas, it's one of the few out there as of recent that has such a unique system of energy, I really thank you for thinking out side the box. I would love including it in my server and modpack, but the server uses Gold as it's currency and this would completely break the economy.

**Comment by pixlepix** [comment]
Just nerfed the aura crystal recipe to give 2 instead of 16. These 'resupply aura' setups have always been intended, but they might have gotten a bit powerful.

If gold transmutation messes with your server balance, it can be disabled using modtweaker.
