### ISSUE TITLE
Textures reversed

### ISSUE THREAD

**Issue by OldOpa** [pixlepix/Aura-Cascade#81]
The texture of arcane yellow gem and arcane orange gem are reversed.

Also a balancing point: Like Vazkii changed the endoflames to cap at a certain point ... do it the same with your burning pumps since there is no challenging point if a pump can run 17 days with a aeternalis fuel block.

**Comment by OldOpa** [comment]
Also I'm trying the miner. It would be good if the fortifed blocks save their damage when they are broken (repairing themselves while in itemstack?)

**Comment by pixlepix** [comment]
The gem textures should have been fixed a while ago.

If someone wants to use EE3, let them.
